#!/bin/bash

ARCH=("amd64" "arm64v8")
for arch in ${ARCH[@]}; do
  base="${arch}"
  if [[ "${arch}" == "amd64" ]]; then
    base="docker.io"
  fi

  echo "docker build . --build-arg ARCH=${base} -t paulhybryant/docker-aria2:${arch}"
  docker build . --build-arg ARCH=${base} -t paulhybryant/docker-aria2:${arch}
  echo "docker push paulhybryant/docker-aria2:${arch}"
  docker push paulhybryant/docker-aria2:${arch}
done
